### ISSUE TITLE
Link in the README redirects to an admin login page.

### ISSUE THREAD

**Issue by sww** [fortitude/fortitude-sass#23]
The https://hired.com/library link goes to an admin login page - probably not the best page to showcase the framework.

**Comment by lifeiscontent** [comment]
@sww thanks for opening the issue. We've been actively working on the library and hopefully we'll push out the new update this week. I'll ping you when its been merged and the library is public again.

Sorry for the inconvenience.

**Comment by mmahalwy** [comment]
+1 just discovered this too

**Comment by lifeiscontent** [comment]
@mmahalwy awesome, glad to see interest. Will try to get to it by EOD Friday. just have a few more things to document then it should be good to go.

**Comment by mmahalwy** [comment]
Awesome! Thanks @lifeiscontent!

**Comment by lifeiscontent** [comment]
@sww @mmahalwy updated! :+1: https://hired.com/library

**Comment by mmahalwy** [comment]
@lifeiscontent looks awesome! Haml eveerrrrryywhere :) 

PS - I emailed you

**Comment by lifeiscontent** [comment]
@mmahalwy Yep, the fortitude.io site will be updated soon with an HTML version of something similar to this.

It's what we have so far to showcase the power of fortitude, but some big updates are coming!
