### ISSUE TITLE
easy way to enable all the things

### ISSUE THREAD

**Issue by wnadeau** [fortitude/fortitude-sass#30]
i love that fortitude doesn't force me into any paradigm, but I hate having to opt-in to all of the useful things. (impedes discovery and usability)

it'd be great if I could just include a file or call a function and turn on everything

**Comment by agius** [comment]
They should all be on by default. >95% of people just want the damn framework with all the nice toys. You can set the variables to remove certain components if they're causing you trouble, or you have unrealistic expectations about trimming css size.

**Comment by lifeiscontent** [comment]
this is done in #49
