### ISSUE TITLE
jquery api doesn't jive with mixin API

### ISSUE THREAD

**Issue by wnadeau** [fortitude/fortitude-sass#32]
@agius right now you can't initialize a jquery component for a class that uses the mixin API for a given thing.

```haml
%ul.example-tabs
  %li.example-tabs__item
```
```sass
.example-tabs {
  @include tabs-navigation;
}
.example-tabs__item { 
  @include tabs-navigation__item;
}
```

the current jquery tabs implementation only queries `.tabs-navigation`. 
Was this an explicit decision or did this case just not come up since the mixin API is still new?

**Comment by wnadeau** [comment]
what if we also listened to events on `.js-tabs` ?

**Comment by lifeiscontent** [comment]
@wnadeau can this be closed?
