### ISSUE TITLE
jquery api is funny to include in a *-sass repo

### ISSUE THREAD

**Issue by wnadeau** [fortitude/fortitude-sass#37]
the name of this repo sort of leaves out room for JS anything.

lol

**Comment by agius** [comment]
[bootstrap-sass javascript dir](https://github.com/twbs/bootstrap-sass/tree/master/assets/javascripts)

More gems + more repos = harder for users to set up, harder for us and for users to maintain.

**Comment by wnadeau** [comment]
oh nice, there's precedent on a sass-fork of bootstrap.

i'm not sure if that gives us the excuse to also have a tightly scoped name.

i agree multiple repos would be overcomplex, but what do you think about the value of renaming it? (What's in a name?)

ah fuck it, it's not worth it.

still kinda weird though.
