### ISSUE TITLE
Following install instructions - doesn't work

### ISSUE THREAD

**Issue by rstormsf** [fortitude/fortitude-sass#60]
http://fortitude.io/getting_started.html

included gem, bundled, I don't get what I want :-( 
There are probably some dependencies left.

did 

``` sass
@import "fortitude";
```

copied/pasted rendered DOM tree from hired.com to some static html and looks like this
https://www.evernote.com/l/AIhnv1n9oEpHb6pM38_sOsl_VhJCrTYLR1U

**Comment by lifeiscontent** [comment]
Alright, I'm gonna spend some time in the coming weeks to polish off the on-boarding for the site and get things usable again. I'm sorry for the frustration. Again, thanks for checking out the project and adding the issues. :+1:
