### ISSUE TITLE
Form Input/Select Helper Classes that Match Button Sizes

### ISSUE THREAD

**Issue by jeromechoo** [fortitude/fortitude-sass#64]
![screen shot 2015-09-07 at 10 12 04 am](https://cloud.githubusercontent.com/assets/3942955/9719342/ef73243a-5548-11e5-9821-a14c38cd25d7.png)

It would be helpful to be able to have some helper classes for input/select elements that match it against button sizes. Something like input--large and input--small would be amazing. See the use case above. I have my own bootstrap addition to the CSS in order to make this happen now, but I figured this would be helpful for more people.

If this isn't struck down, I'd be happy to submit a pull request.

**Comment by lifeiscontent** [comment]
@jdchizzle would love to see your submission. Just make sure to bump the version in bower, npm, and the gemfile :+1:

**Comment by lifeiscontent** [comment]
we're always looking for submissions to help make front-end development easier, so please keep these coming! :smile:

**Comment by lifeiscontent** [comment]
@jdchizzle any updates?

**Comment by jdchizzle** [comment]
@lifeiscontent Added the SCSS, but I don't normally use Ruby or gems and ```grunt test``` was dropping an error on me. I ran it with --force and the /dist folder came up with zero byte files so I gave up. Any ideas?

Result of GRUNT TEST

    Running "sass:test" (sass) task
    Warning: 
    bundleExec options set but no Bundler executable found in your PATH.
    More info: https://github.com/gruntjs/grunt-contrib-sass
     Use --force to continue.

    Aborted due to warnings.

Results of GRUNT --FORCE BUILD

    Running "sass:dist" (sass) task
    Warning: 
	bundleExec options set but no Bundler executable found in your PATH.
	More info: https://github.com/gruntjs/grunt-contrib-sass
	 Used --force, continuing.
	Warning: spawn bundle ENOENT Used --force, continuing.
	Warning: spawn bundle ENOENT Used --force, continuing.

	Running "sass:min" (sass) task
	Warning: 
	bundleExec options set but no Bundler executable found in your PATH.
	More info: https://github.com/gruntjs/grunt-contrib-sass
	 Used --force, continuing.
	Warning: spawn bundle ENOENT Used --force, continuing.
	Warning: spawn bundle ENOENT Used --force, continuing.

	Running "autoprefixer:dist" (autoprefixer) task
	Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
	File dist/fortitude-theme.css created.
	Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
	File dist/fortitude-theme.min.css created.
	Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
	File dist/fortitude.css created.
	Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
	File dist/fortitude.min.css created.

	Running "concat:dist" (concat) task
	File dist/fortitude.js created.

	Running "uglify:dist" (uglify) task
	>> Destination dist/fortitude.jquery.js not written because src files were empty.
	>> No files created.

	Running "copy:dist" (copy) task
	Copied 2 files

	Done, but with warnings.

**Comment by lifeiscontent** [comment]
@jdchizzle ah yeah, maybe we have a dependency on ruby. I'll do some investigating later. Until then, I think I'll just make the update.
